#!/bin/bash
#python3 ../disassemble/csv2veriloghex.py ../disassemble/test_sim.csv ../disassemble/test_sim.hex 
#python3 hex2mem48.py  89KLR_951.hex 89KLR_951.mem
rm ../../tmp/klr/i8048_regression_tb.vvp

iverilog -o ../../tmp/klr/i8048_regression_tb.vvp -I bench/verilog bench/verilog/i8048_core_tb.v rtl/verilog/i8048_core.v
vvp ../../tmp/klr/i8048_regression_tb.vvp +fst=../../tmp/klr/fst/i8048_regression_tb.fst
source  ../8051_Debug/bin/activate
python3 ../disassemble/xlsx2veriloghex.py ../bin_images/klr/87KLR951.xlsx ../bin_images/klr/test_sim.hex
python3 ../disassemble/xlsxmembyte2veriloghex.py  ../bin_images/klr/87KLR951.xlsx ../bin_images/klr/memory_byte_map.hex
python3 ../disassemble/xlsxinstr2veriloghex.py  ../bin_images/klr/87KLR951.xlsx
deactivate
mv asm_instr.hex ../bin_images/klr
mv asm_opcode_ins.hex ../bin_images/klr
mv asm_operands_numeric.hex ../bin_images/klr
mv asm_operands.hex ../bin_images/klr

