#!/bin/bash
#python3 ../disassemble/csv2veriloghex.py ../disassemble/test_sim.csv ../disassemble/test_sim.hex 
#python3 hex2mem48.py  89KLR_951.hex 89KLR_951.mem
rm ../../tmp/gemini8048/i8048_regression_tb.vvp

iverilog -o ../../tmp/gemini8048/i8048_regression_tb.vvp -I bench/verilog bench/verilog/i8048_core_tb.v rtl/verilog/i8048_core.v
vvp ../../tmp/gemini8048/i8048_regression_tb.vvp +fst=../../tmp/gemini8048/fst/i8048_regression_tb.fst
python3 ../disassemble/xlsx2veriloghex.py bin/87KLR951.xlsx bin/test_sim.hex 
python3 ../disassemble/xlsxmembyte2veriloghex.py  bin/87KLR951.xlsx bin/memory_byte_map.hex
python3 ../disassemble/xlsxinstr2veriloghex.py  bin/87KLR951.xlsx 
mv asm_instr.hex bin
mv asm_opcode_ins.hex bin
mv asm_operands_numeric.hex bin
mv asm_operands.hex bin

