#!/bin/bash
#python3 ../disassemble/csv2veriloghex.py ../disassemble/test_sim.csv ../disassemble/test_sim.hex 
#python3 hex2mem48.py  89KLR_951.hex 89KLR_951.mem
rm ../../tmp/gemini8048/i8048_regression_tb.vvp
rm ../../tmp/gemini8048/i8048.vvp
rm ../../tmp/gemini8048/951klr.log
rm ../../tmp/gemini8048/debug1.log
rm ../../tmp/gemini8048/951klr_dedupe.log
rm ../../tmp/gemini8048/hex/ram_out.hex
rm ../../tmp/gemini8048/hex/rom_out.hex

iverilog -o ../../tmp/gemini8048/i8048_regression_tb.vvp -I bench/verilog bench/verilog/i8048_core_tb.v rtl/verilog/i8048_core.v
vvp ../../tmp/gemini8048/i8048_regression_tb.vvp +fst=../../tmp/gemini8048/fst/i8048_regression_tb.fst
iverilog -o ../../tmp/gemini8048/i8048.vvp   -f files -I rtl/verilog -I bench/verilog -I ../claude_8051/bench/verilog -s klr_tb 
#iverilog -o ../../tmp/gemini8048/i8048.vvp -DKLR_DEBUG  -f files -I rtl/verilog -I bench/verilog -I ../claude_8051/bench/verilog -s klr_tb 
source  ../8051_Debug/bin/activate
python3 ../disassemble/xlsx2veriloghex.py bin/87KLR951.xlsx bin/test_sim.hex 
python3 ../disassemble/xlsxmembyte2veriloghex.py  bin/87KLR951.xlsx bin/memory_byte_map.hex
python3 ../disassemble/xlsxinstr2veriloghex.py  bin/87KLR951.xlsx 
mv asm_instr.hex bin
mv asm_opcode_ins.hex bin
mv asm_operands_numeric.hex bin
mv asm_operands.hex bin

vvp ../../tmp/gemini8048/i8048.vvp > ../../tmp/gemini8048/951klr.log
mv ram_out.hex ../../tmp/gemini8048/hex 
mv rom_out.hex ../../tmp/gemini8048/hex 
cat ../../tmp/gemini8048/951klr.log | grep -v "^\t" | grep -v "^label" > ../../tmp/gemini8048/debug1.log
cat ../../tmp/gemini8048/debug1.log | python3 ../../claude_8051/dedupe.py > ../../tmp/gemini8048/951klr_dedupe.log
